import eslintConfigPrettier from 'eslint-config-prettier';
import js from '@eslint/js';

export default [
    js.configs.recommended,
    eslintConfigPrettier,
    {
        files: ['static/**/*.js'],
        languageOptions: {
            ecmaVersion: 'latest',
            sourceType: 'script',
            globals: {
                window: 'readonly',
                document: 'readonly',
                console: 'readonly',
                setTimeout: 'readonly',
                setInterval: 'readonly',
                clearTimeout: 'readonly',
                clearInterval: 'readonly',
                requestAnimationFrame: 'readonly',
                cancelAnimationFrame: 'readonly',
                fetch: 'readonly',
                WebSocket: 'readonly',
                HTMLElement: 'readonly',
                Event: 'readonly',
                KeyboardEvent: 'readonly',
                MutationObserver: 'readonly',
                IntersectionObserver: 'readonly',
                ResizeObserver: 'readonly',
                AbortController: 'readonly',
                URLSearchParams: 'readonly',
                FormData: 'readonly',
                Headers: 'readonly',
                Response: 'readonly',
                Request: 'readonly',
                navigator: 'readonly',
                location: 'readonly',
                history: 'readonly',
                localStorage: 'readonly',
                sessionStorage: 'readonly',
                CustomEvent: 'readonly',
                alert: 'readonly',
                confirm: 'readonly',
                prompt: 'readonly',
                performance: 'readonly',
                queueMicrotask: 'readonly',
                structuredClone: 'readonly',
                Blob: 'readonly',
                URL: 'readonly',
                Map: 'readonly',
                Set: 'readonly',
                Promise: 'readonly',
                JSON: 'readonly',
                Math: 'readonly',
                parseInt: 'readonly',
                parseFloat: 'readonly',
                isNaN: 'readonly',
                isFinite: 'readonly',
                encodeURIComponent: 'readonly',
                decodeURIComponent: 'readonly',
                btoa: 'readonly',
                atob: 'readonly',
            },
        },
        rules: {
            'no-unused-vars': ['warn', {
                    argsIgnorePattern: '^_',
                    varsIgnorePattern: '^sequencer$',
                    caughtErrorsIgnorePattern: '^_',
                }],
        },
    },
];
